/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package versus.Interface;

import jaco.mp3.player.MP3Player;
import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.ImageIcon;

/**
 *
 * @author Louis
 */
public class MainMenu extends javax.swing.JPanel {

    public static MP3Player mainMenuMusic;
    public static MP3Player menuButton;
    
    public static void playMainMusic(){
        java.net.URL musicURL = MainMenu.class.getClassLoader().getResource("assets/musics/main_menu.mp3");
        mainMenuMusic = new MP3Player(musicURL);
        mainMenuMusic.setRepeat(true);
        mainMenuMusic.play();
    }
    public static void stopMainMusic() {
        if (mainMenuMusic != null) {
            mainMenuMusic.stop();
        }
    }
    public static void buttonSound() {
        java.net.URL soundURL = MainMenu.class.getClassLoader().getResource("assets/sounds/button_main_menu.mp3");
        menuButton = new MP3Player(soundURL);
        menuButton.play();
    }
    
    
    // =========================================================================
    // ==== SCALING THE ELEMENTS OF THE MAIN MENU T0 THE FRAME'S DIMENSIONS ====
    // =========================================================================
    public void scaleMenu(int frameWidth, int frameHeight){
        
        // SCALLING THE FOREGROUND
        double widthScale = (double) frameWidth / main_foreground.getIcon().getIconWidth();
        double heightScale = (double) frameHeight / main_foreground.getIcon().getIconHeight();
        double scale = Math.min(widthScale, heightScale);
        
        Image scaledImage = ((ImageIcon) main_foreground.getIcon()).getImage().getScaledInstance(
            (int) (main_foreground.getIcon().getIconWidth() * scale),
            (int) (main_foreground.getIcon().getIconHeight() * scale),
            Image.SCALE_SMOOTH);
        
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        main_foreground.setIcon(scaledIcon);
        main_foreground.setBounds(0, 0, frameWidth, frameHeight); // x, y, width, height

        // SCALLING BACKGROUND ANIMATION
        widthScale = (double) frameWidth / main_backgroundAnimation.getIcon().getIconWidth();
        heightScale = (double) frameHeight / main_backgroundAnimation.getIcon().getIconHeight();
        scale = Math.min(widthScale, heightScale);
        
        scaledImage = ((ImageIcon) main_backgroundAnimation.getIcon()).getImage().getScaledInstance(
            (int) (main_backgroundAnimation.getIcon().getIconWidth() * scale),
            (int) (main_backgroundAnimation.getIcon().getIconHeight() * scale),
            Image.SCALE_DEFAULT);
        
        scaledIcon = new ImageIcon(scaledImage);
        main_backgroundAnimation.setIcon(scaledIcon);
        main_backgroundAnimation.setBounds(0, 0, frameWidth, frameHeight); // x, y, width, height
        
        // SCALLING THE BUTTONS
        Rectangle currentBounds = main_playButton.getBounds();
        int vertical_placement = (int) ((frameHeight - currentBounds.height) / 1.35);
        int horizontal_placement = (frameWidth - currentBounds.width) / 2;
        main_playButton.setBounds(horizontal_placement, vertical_placement, currentBounds.width, currentBounds.height);
        
        currentBounds = main_optionsButton.getBounds();
        vertical_placement = (int) ((frameHeight - currentBounds.height) / 1.2);
        horizontal_placement = (int) ((frameWidth - currentBounds.width) / 1.891);
        main_optionsButton.setBounds( horizontal_placement, vertical_placement, currentBounds.width, currentBounds.height);
        
        currentBounds = main_quitButton.getBounds();
        vertical_placement = (int) ((frameHeight - currentBounds.height) / 1.07);
        horizontal_placement = (frameWidth - currentBounds.width) / 2;
        main_quitButton.setBounds(horizontal_placement, vertical_placement, currentBounds.width, currentBounds.height);
        
    }
    


    // #####################
    // #### CONSTRUCTOR ####
    // #####################
    public MainMenu() {
        initComponents();

        playMainMusic();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_playButton = new javax.swing.JButton();
        main_quitButton = new javax.swing.JButton();
        main_optionsButton = new javax.swing.JButton();
        main_foreground = new javax.swing.JLabel();
        main_backgroundAnimation = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(null);

        main_playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menus/play_button.png"))); // NOI18N
        main_playButton.setBorder(null);
        main_playButton.setBorderPainted(false);
        main_playButton.setContentAreaFilled(false);
        main_playButton.setFocusPainted(false);
        main_playButton.setName("playButton"); // NOI18N
        main_playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_playButtonActionPerformed(evt);
            }
        });
        add(main_playButton);
        main_playButton.setBounds(570, 485, 140, 60);

        main_quitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menus/quit_button.png"))); // NOI18N
        main_quitButton.setBorder(null);
        main_quitButton.setBorderPainted(false);
        main_quitButton.setContentAreaFilled(false);
        main_quitButton.setFocusPainted(false);
        main_quitButton.setName("playButton"); // NOI18N
        main_quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_quitButtonActionPerformed(evt);
            }
        });
        add(main_quitButton);
        main_quitButton.setBounds(570, 618, 140, 60);

        main_optionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menus/options_button.png"))); // NOI18N
        main_optionsButton.setBorder(null);
        main_optionsButton.setBorderPainted(false);
        main_optionsButton.setContentAreaFilled(false);
        main_optionsButton.setFocusPainted(false);
        main_optionsButton.setName("playButton"); // NOI18N
        main_optionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_optionsButtonActionPerformed(evt);
            }
        });
        add(main_optionsButton);
        main_optionsButton.setBounds(570, 552, 200, 60);

        main_foreground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menus/main_menu.png"))); // NOI18N
        add(main_foreground);
        main_foreground.setBounds(0, 0, 1280, 720);

        main_backgroundAnimation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menus/background_animation.gif"))); // NOI18N
        add(main_backgroundAnimation);
        main_backgroundAnimation.setBounds(0, 0, 1280, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void main_playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_playButtonActionPerformed
            this.buttonSound();
            this.stopMainMusic();
            this.setVisible(false);
           
            Versus.getPreparation().setVisible(true);
            Preparation.playPreparationMusic();
    }//GEN-LAST:event_main_playButtonActionPerformed

    private void main_optionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_optionsButtonActionPerformed
        MainMenu.buttonSound();
        this.setVisible(false);
        Versus.getOptions().setVisible(true);
    }//GEN-LAST:event_main_optionsButtonActionPerformed

    private void main_quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_quitButtonActionPerformed
        this.stopMainMusic();
        MainMenu.buttonSound();
        System.exit(0);
    }//GEN-LAST:event_main_quitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel main_backgroundAnimation;
    protected javax.swing.JLabel main_foreground;
    protected javax.swing.JButton main_optionsButton;
    protected javax.swing.JButton main_playButton;
    protected javax.swing.JButton main_quitButton;
    // End of variables declaration//GEN-END:variables
}
