/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package versus.Interface;

import java.awt.Color;
import javax.swing.JColorChooser;
import static versus.Interface.Versus.updateProperties;

/**
 *
 * @author Louis
 */
public class Options extends javax.swing.JPanel {

    // ===============================================================
    // ==== SCALE THE PANEL'S ELEMENTS TO THE WINDOW'S DIMENSIONS ====
    // ===============================================================
    public void scaleMenu(int frameWidth, int frameHeight){
        // void
    }
    
    // #####################
    // #### CONSTRUCTOR ####
    // #####################
    public Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        option_dimension_choice = new javax.swing.ButtonGroup();
        options_panel = new keeptoo.KGradientPanel();
        options_BackButton = new javax.swing.JButton();
        options_button_fullscreen = new javax.swing.JRadioButton();
        options_button_1080p = new javax.swing.JRadioButton();
        options_button_720p = new javax.swing.JRadioButton();
        options_button_autodim = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        options_buttonStartP1 = new javax.swing.JButton();
        options_buttonEndP1 = new javax.swing.JButton();
        options_buttonStartP2 = new javax.swing.JButton();
        options_buttonEndP2 = new javax.swing.JButton();
        options_buttonStartGen = new javax.swing.JButton();
        options_buttonEndGen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        options_colorExampleP1 = new keeptoo.KGradientPanel();
        options_colorExampleP2 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        options_panel.setPreferredSize(new java.awt.Dimension(1280, 720));
        options_panel.setLayout(null);

        options_BackButton.setText("Back");
        options_BackButton.setFocusPainted(false);
        options_BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_BackButtonActionPerformed(evt);
            }
        });
        options_panel.add(options_BackButton);
        options_BackButton.setBounds(220, 502, 170, 82);

        option_dimension_choice.add(options_button_fullscreen);
        options_button_fullscreen.setText("Fullscreen");
        options_button_fullscreen.setEnabled(false);
        options_button_fullscreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_button_fullscreenActionPerformed(evt);
            }
        });
        options_panel.add(options_button_fullscreen);
        options_button_fullscreen.setBounds(220, 292, 140, 21);

        option_dimension_choice.add(options_button_1080p);
        options_button_1080p.setText("1080p");
        options_button_1080p.setEnabled(false);
        options_panel.add(options_button_1080p);
        options_button_1080p.setBounds(220, 325, 140, 21);

        option_dimension_choice.add(options_button_720p);
        options_button_720p.setText("720p");
        options_panel.add(options_button_720p);
        options_button_720p.setBounds(220, 358, 140, 21);

        option_dimension_choice.add(options_button_autodim);
        options_button_autodim.setText("Scale automatically");
        options_button_autodim.setEnabled(false);
        options_panel.add(options_button_autodim);
        options_button_autodim.setBounds(220, 391, 140, 21);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Click to apply the color");
        options_panel.add(jLabel1);
        jLabel1.setBounds(641, 138, 403, 50);

        options_buttonStartP1.setText("First color P1");
        options_buttonStartP1.setFocusPainted(false);
        options_buttonStartP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_buttonStartP1ActionPerformed(evt);
            }
        });
        options_panel.add(options_buttonStartP1);
        options_buttonStartP1.setBounds(790, 200, 140, 45);

        options_buttonEndP1.setText("Second color P1");
        options_buttonEndP1.setFocusPainted(false);
        options_buttonEndP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_buttonEndP1ActionPerformed(evt);
            }
        });
        options_panel.add(options_buttonEndP1);
        options_buttonEndP1.setBounds(790, 250, 140, 45);

        options_buttonStartP2.setText("First color P2");
        options_buttonStartP2.setFocusPainted(false);
        options_buttonStartP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_buttonStartP2ActionPerformed(evt);
            }
        });
        options_panel.add(options_buttonStartP2);
        options_buttonStartP2.setBounds(940, 200, 140, 45);

        options_buttonEndP2.setText("Second color P2");
        options_buttonEndP2.setToolTipText("");
        options_buttonEndP2.setFocusPainted(false);
        options_buttonEndP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_buttonEndP2ActionPerformed(evt);
            }
        });
        options_panel.add(options_buttonEndP2);
        options_buttonEndP2.setBounds(940, 250, 140, 45);

        options_buttonStartGen.setText("First gen color");
        options_buttonStartGen.setToolTipText("");
        options_buttonStartGen.setFocusPainted(false);
        options_buttonStartGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_buttonStartGenActionPerformed(evt);
            }
        });
        options_panel.add(options_buttonStartGen);
        options_buttonStartGen.setBounds(640, 200, 140, 45);

        options_buttonEndGen.setText("Second gen color");
        options_buttonEndGen.setFocusPainted(false);
        options_buttonEndGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options_buttonEndGenActionPerformed(evt);
            }
        });
        options_panel.add(options_buttonEndGen);
        options_buttonEndGen.setBounds(640, 250, 140, 45);

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Options");
        options_panel.add(jLabel2);
        jLabel2.setBounds(220, 130, 319, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose the window's properties");
        options_panel.add(jLabel3);
        jLabel3.setBounds(220, 248, 342, 32);

        options_colorExampleP1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        options_colorExampleP1.setkEndColor(new java.awt.Color(255, 102, 102));
        options_colorExampleP1.setkStartColor(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout options_colorExampleP1Layout = new javax.swing.GroupLayout(options_colorExampleP1);
        options_colorExampleP1.setLayout(options_colorExampleP1Layout);
        options_colorExampleP1Layout.setHorizontalGroup(
            options_colorExampleP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        options_colorExampleP1Layout.setVerticalGroup(
            options_colorExampleP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        options_panel.add(options_colorExampleP1);
        options_colorExampleP1.setBounds(530, 350, 310, 310);

        options_colorExampleP2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        options_colorExampleP2.setkEndColor(new java.awt.Color(0, 102, 204));
        options_colorExampleP2.setkStartColor(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout options_colorExampleP2Layout = new javax.swing.GroupLayout(options_colorExampleP2);
        options_colorExampleP2.setLayout(options_colorExampleP2Layout);
        options_colorExampleP2Layout.setHorizontalGroup(
            options_colorExampleP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        options_colorExampleP2Layout.setVerticalGroup(
            options_colorExampleP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        options_panel.add(options_colorExampleP2);
        options_colorExampleP2.setBounds(850, 350, 310, 310);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Player 1 colors");
        options_panel.add(jLabel4);
        jLabel4.setBounds(590, 322, 89, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Player 2 colors");
        options_panel.add(jLabel5);
        jLabel5.setBounds(848, 322, 89, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(options_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(options_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void options_BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options_BackButtonActionPerformed
        this.setVisible(false);
        Versus.getMain().setVisible(true);
    }//GEN-LAST:event_options_BackButtonActionPerformed

    private void options_button_fullscreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options_button_fullscreenActionPerformed

    }//GEN-LAST:event_options_button_fullscreenActionPerformed

    private void options_buttonStartGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options_buttonStartGenActionPerformed
            Color newColor = JColorChooser.showDialog(this, "Select a color", Color.WHITE);
            if(newColor != null){ // if the user validates a color, then...
                this.options_panel.kStartColor = newColor;
                Versus.getPreparation().descriptionPanel.kStartColor = newColor;
                Versus.getCombat().actionPanel.kStartColor = newColor;
                Versus.getCombat().choicePanel.kStartColor = newColor;
                Versus.getCombat().magicPanel.kStartColor = newColor;
                Versus.getCombat().itemsPanel.kStartColor = newColor;
                Versus.getCombat().defensePanel.kStartColor = newColor;
                Versus.getCombat().attackPanel.kStartColor = newColor;
                

                String newColorValues = newColor.getRed() + "," + newColor.getGreen() + "," + newColor.getBlue();
                Versus.updateProperties(newColorValues,"GeneralStartColor");
                this.setVisible(false); // the JFrame reappears, without it's border
                this.setVisible(true); 
            }
    }//GEN-LAST:event_options_buttonStartGenActionPerformed

    private void options_buttonEndGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options_buttonEndGenActionPerformed
        Color newColor = JColorChooser.showDialog(this, "Select a color", Color.WHITE);
        if(newColor != null){ // if the user validates a color, then...
            this.options_panel.kEndColor = newColor;
            Versus.getPreparation().descriptionPanel.kEndColor = newColor;
            Versus.getCombat().actionPanel.kEndColor = newColor;
                Versus.getCombat().choicePanel.kEndColor = newColor;
                Versus.getCombat().magicPanel.kEndColor = newColor;
                Versus.getCombat().itemsPanel.kEndColor = newColor;
                Versus.getCombat().defensePanel.kEndColor = newColor;
                Versus.getCombat().attackPanel.kEndColor = newColor;

            String newColorValues = newColor.getRed() + "," + newColor.getGreen() + "," + newColor.getBlue();
            updateProperties(newColorValues,"GeneralEndColor");
            this.setVisible(false); // the JFrame reappears, without it's border
            this.setVisible(true); 
        }
    }//GEN-LAST:event_options_buttonEndGenActionPerformed

    private void options_buttonStartP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options_buttonStartP1ActionPerformed
        Color newColor = JColorChooser.showDialog(this, "Select a color", Color.WHITE);
        if(newColor != null){ // if the user validates a color, then...
            Versus.getPreparation().preparation_P1.kStartColor = newColor;
            Versus.getPreparation().P1_classSelection.kStartColor = newColor;
            Versus.getPreparation().P1_itemSelection.kStartColor = newColor;
            Versus.getCombat().P1_teamStats.kStartColor = newColor;
            this.options_colorExampleP1.kStartColor = newColor;

            String newColorValues = newColor.getRed() + "," + newColor.getGreen() + "," + newColor.getBlue();
            updateProperties(newColorValues,"player1StartColor");
            this.setVisible(false); // the JFrame reappears, without it's border
            this.setVisible(true); 
        }
    }//GEN-LAST:event_options_buttonStartP1ActionPerformed

    private void options_buttonEndP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options_buttonEndP1ActionPerformed
        Color newColor = JColorChooser.showDialog(this, "Select a color", Color.WHITE);
         if(newColor != null){ // if the user validates a color, then...
             Versus.getPreparation().preparation_P1.kEndColor = newColor;
             Versus.getPreparation().P1_classSelection.kEndColor = newColor;
             Versus.getPreparation().P1_itemSelection.kEndColor = newColor;
             Versus.getCombat().P1_teamStats.kEndColor = newColor;
             this.options_colorExampleP1.kEndColor = newColor; // ùùùùù

             String newColorValues = newColor.getRed() + "," + newColor.getGreen() + "," + newColor.getBlue();
             updateProperties(newColorValues,"player1EndColor");
             this.setVisible(false); // the JFrame reappears, without it's border
             this.setVisible(true); 
         }
    }//GEN-LAST:event_options_buttonEndP1ActionPerformed

    private void options_buttonStartP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options_buttonStartP2ActionPerformed
        Color newColor = JColorChooser.showDialog(this, "Select a color", Color.WHITE);
        if(newColor != null){ // if the user validates a color, then...
            Versus.getPreparation().preparation_P2.kStartColor = newColor;
            Versus.getPreparation().P2_classSelection.kStartColor = newColor;
            Versus.getPreparation().P2_itemSelection.kStartColor = newColor;
            Versus.getCombat().P2_teamStats.kStartColor = newColor;
            this.options_colorExampleP2.kStartColor = newColor;

            String newColorValues = newColor.getRed() + "," + newColor.getGreen() + "," + newColor.getBlue();
            updateProperties(newColorValues,"player2StartColor");
            this.setVisible(false); // the JFrame reappears, without it's border
            this.setVisible(true); 
        }
    }//GEN-LAST:event_options_buttonStartP2ActionPerformed

    private void options_buttonEndP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options_buttonEndP2ActionPerformed
        Color newColor = JColorChooser.showDialog(this, "Select a color", Color.WHITE);
        if(newColor != null){ // if the user validates a color, then...
            Versus.getPreparation().preparation_P2.kEndColor = newColor;
            Versus.getPreparation().P2_classSelection.kEndColor = newColor;
            Versus.getPreparation().P2_itemSelection.kEndColor = newColor;
            Versus.getCombat().P2_teamStats.kEndColor = newColor;
            this.options_colorExampleP2.kEndColor = newColor;

            String newColorValues = newColor.getRed() + "," + newColor.getGreen() + "," + newColor.getBlue();
            updateProperties(newColorValues,"player2EndColor");
            this.setVisible(false); // the JFrame reappears, without it's border
            this.setVisible(true); 
        }
    }//GEN-LAST:event_options_buttonEndP2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.ButtonGroup option_dimension_choice;
    protected javax.swing.JButton options_BackButton;
    protected javax.swing.JButton options_buttonEndGen;
    protected javax.swing.JButton options_buttonEndP1;
    protected javax.swing.JButton options_buttonEndP2;
    protected javax.swing.JButton options_buttonStartGen;
    protected javax.swing.JButton options_buttonStartP1;
    protected javax.swing.JButton options_buttonStartP2;
    protected javax.swing.JRadioButton options_button_1080p;
    protected javax.swing.JRadioButton options_button_720p;
    protected javax.swing.JRadioButton options_button_autodim;
    protected javax.swing.JRadioButton options_button_fullscreen;
    protected keeptoo.KGradientPanel options_colorExampleP1;
    protected keeptoo.KGradientPanel options_colorExampleP2;
    protected keeptoo.KGradientPanel options_panel;
    // End of variables declaration//GEN-END:variables
}